export const toiletCubicleCities = [
  { label: "Delhi", href: "/toilet-cubicle-in-delhi" },
  { label: "New Delhi", href: "/toilet-cubicle-in-new-delhi" },
  { label: "Gurugram", href: "/toilet-cubicle-in-gurugram" },
  { label: "Faridabad", href: "/toilet-cubicle-in-faridabad" },
  { label: "Noida", href: "/toilet-cubicle-in-noida" },
  { label: "Greater Noida", href: "/toilet-cubicle-in-greater-noida" },
  { label: "Ghaziabad", href: "/toilet-cubicle-in-ghaziabad" },
  { label: "Sonipat", href: "/toilet-cubicle-in-sonipat" },
  { label: "Bahadurgarh", href: "/toilet-cubicle-in-bahadurgarh" },
  { label: "Panipat", href: "/toilet-cubicle-in-panipat" },
  { label: "Rohtak", href: "/toilet-cubicle-in-rohtak" },
  { label: "Rewari", href: "/toilet-cubicle-in-rewari" },
  { label: "Hapur", href: "/toilet-cubicle-in-hapur" },
  { label: "Meerut", href: "/toilet-cubicle-in-meerut" },
  { label: "Baghpat", href: "/toilet-cubicle-in-baghpat" },
  { label: "Bulandshahr", href: "/toilet-cubicle-in-bulandshahr" },
  { label: "Muzaffarnagar", href: "/toilet-cubicle-in-muzaffarnagar" },
  { label: "Shamli", href: "/toilet-cubicle-in-shamli" },
  { label: "Palwal", href: "/toilet-cubicle-in-palwal" },
  { label: "Jhajjar", href: "/toilet-cubicle-in-jhajjar" },
  { label: "Karnal", href: "/toilet-cubicle-in-karnal" },
  { label: "Hisar", href: "/toilet-cubicle-in-hisar" },
  { label: "Ambala", href: "/toilet-cubicle-in-ambala" },
  { label: "Kurukshetra", href: "/toilet-cubicle-in-kurukshetra" },
  { label: "Yamunanagar", href: "/toilet-cubicle-in-yamunanagar" },
  { label: "Panchkula", href: "/toilet-cubicle-in-panchkula" },
  { label: "Sirsa", href: "/toilet-cubicle-in-sirsa" },
  { label: "Bhiwani", href: "/toilet-cubicle-in-bhiwani" },
  { label: "Jind", href: "/toilet-cubicle-in-jind" },
  { label: "Kaithal", href: "/toilet-cubicle-in-kaithal" },
  { label: "Fatehabad", href: "/toilet-cubicle-in-fatehabad" },
  { label: "Narnaul", href: "/toilet-cubicle-in-narnaul" },
  { label: "Mahendragarh", href: "/toilet-cubicle-in-mahendragarh" },
  { label: "Charkhi Dadri", href: "/toilet-cubicle-in-charkhi-dadri" },
  { label: "Nuh", href: "/toilet-cubicle-in-nuh" },
  { label: "Dharuhera", href: "/toilet-cubicle-in-dharuhera" },
  { label: "Bawal", href: "/toilet-cubicle-in-bawal" },
  { label: "Hansi", href: "/toilet-cubicle-in-hansi" },
  { label: "Tohana", href: "/toilet-cubicle-in-tohana" },
  { label: "Narwana", href: "/toilet-cubicle-in-narwana" },

  { label: "Agra", href: "/toilet-cubicle-in-agra" },
  { label: "Mathura", href: "/toilet-cubicle-in-mathura" },
  { label: "Aligarh", href: "/toilet-cubicle-in-aligarh" },
  { label: "Lucknow", href: "/toilet-cubicle-in-lucknow" },
  { label: "Kanpur", href: "/toilet-cubicle-in-kanpur" },
  { label: "Bareilly", href: "/toilet-cubicle-in-bareilly" },
  { label: "Moradabad", href: "/toilet-cubicle-in-moradabad" },
  { label: "Saharanpur", href: "/toilet-cubicle-in-saharanpur" },
  { label: "Firozabad", href: "/toilet-cubicle-in-firozabad" },
  { label: "Ayodhya", href: "/toilet-cubicle-in-ayodhya" },
  { label: "Prayagraj", href: "/toilet-cubicle-in-prayagraj" },
  { label: "Varanasi", href: "/toilet-cubicle-in-varanasi" },
  { label: "Gorakhpur", href: "/toilet-cubicle-in-gorakhpur" },
  { label: "Jhansi", href: "/toilet-cubicle-in-jhansi" },
  { label: "Rampur", href: "/toilet-cubicle-in-rampur" },
  { label: "Rae Bareli", href: "/toilet-cubicle-in-rae-bareli" },
  { label: "Unnao", href: "/toilet-cubicle-in-unnao" },
  { label: "Etawah", href: "/toilet-cubicle-in-etawah" },
  { label: "Mainpuri", href: "/toilet-cubicle-in-mainpuri" },
  { label: "Shahjahanpur", href: "/toilet-cubicle-in-shahjahanpur" },
  { label: "Bulandshahr", href: "/toilet-cubicle-in-bulandshahr" },
  { label: "Sitapur", href: "/toilet-cubicle-in-sitapur" },
  { label: "Lakhimpur", href: "/toilet-cubicle-in-lakhimpur" },
  { label: "Farrukhabad", href: "/toilet-cubicle-in-farrukhabad" },
  { label: "Sultanpur", href: "/toilet-cubicle-in-sultanpur" },
  { label: "Mirzapur", href: "/toilet-cubicle-in-mirzapur" },
  { label: "Ghazipur", href: "/toilet-cubicle-in-ghazipur" },
  { label: "Jaunpur", href: "/toilet-cubicle-in-jaunpur" },
  { label: "Muzaffarnagar", href: "/toilet-cubicle-in-muzaffarnagar" },
  { label: "Aligarh", href: "/toilet-cubicle-in-aligarh" },

  { label: "Jaipur", href: "/toilet-cubicle-in-jaipur" },
  { label: "Alwar", href: "/toilet-cubicle-in-alwar" },
  { label: "Bhiwadi", href: "/toilet-cubicle-in-bhiwadi" },
  { label: "Bharatpur", href: "/toilet-cubicle-in-bharatpur" },
  { label: "Neemrana", href: "/toilet-cubicle-in-neemrana" },
  { label: "Kota", href: "/toilet-cubicle-in-kota" },
  { label: "Ajmer", href: "/toilet-cubicle-in-ajmer" },
  { label: "Jodhpur", href: "/toilet-cubicle-in-jodhpur" },
  { label: "Udaipur", href: "/toilet-cubicle-in-udaipur" },
  { label: "Bikaner", href: "/toilet-cubicle-in-bikaner" },
  { label: "Sikar", href: "/toilet-cubicle-in-sikar" },
  { label: "Bhilwara", href: "/toilet-cubicle-in-bhilwara" },
  { label: "Sri Ganganagar", href: "/toilet-cubicle-in-sri-ganganagar" },
  { label: "Hanumangarh", href: "/toilet-cubicle-in-hanumangarh" },
  { label: "Chittorgarh", href: "/toilet-cubicle-in-chittorgarh" },

  { label: "Gwalior", href: "/toilet-cubicle-in-gwalior" },
  { label: "Morena", href: "/toilet-cubicle-in-morena" },
  { label: "Shivpuri", href: "/toilet-cubicle-in-shivpuri" },
  { label: "Guna", href: "/toilet-cubicle-in-guna" },
  { label: "Bhopal", href: "/toilet-cubicle-in-bhopal" },
  { label: "Indore", href: "/toilet-cubicle-in-indore" },
  { label: "Ujjain", href: "/toilet-cubicle-in-ujjain" },
  { label: "Jabalpur", href: "/toilet-cubicle-in-jabalpur" },
  { label: "Sagar", href: "/toilet-cubicle-in-sagar" },
  { label: "Ratlam", href: "/toilet-cubicle-in-ratlam" },
  { label: "Dewas", href: "/toilet-cubicle-in-dewas" },
  { label: "Rewa", href: "/toilet-cubicle-in-rewa" },
  { label: "Satna", href: "/toilet-cubicle-in-satna" },
  { label: "Vidisha", href: "/toilet-cubicle-in-vidisha" },
  { label: "Mandsaur", href: "/toilet-cubicle-in-mandsaur" },
];


export const restroomCities = [
  { label: "Delhi", href: "/restroom-cubicle-in-delhi" },
  { label: "New Delhi", href: "/restroom-cubicle-in-new-delhi" },
  { label: "Gurugram", href: "/restroom-cubicle-in-gurugram" },
  { label: "Faridabad", href: "/restroom-cubicle-in-faridabad" },
  { label: "Noida", href: "/restroom-cubicle-in-noida" },
  { label: "Greater Noida", href: "/restroom-cubicle-in-greater-noida" },
  { label: "Ghaziabad", href: "/restroom-cubicle-in-ghaziabad" },
  { label: "Sonipat", href: "/restroom-cubicle-in-sonipat" },
  { label: "Bahadurgarh", href: "/restroom-cubicle-in-bahadurgarh" },
  { label: "Panipat", href: "/restroom-cubicle-in-panipat" },
  { label: "Rohtak", href: "/restroom-cubicle-in-rohtak" },
  { label: "Rewari", href: "/restroom-cubicle-in-rewari" },
  { label: "Hapur", href: "/restroom-cubicle-in-hapur" },
  { label: "Meerut", href: "/restroom-cubicle-in-meerut" },
  { label: "Baghpat", href: "/restroom-cubicle-in-baghpat" },
  { label: "Bulandshahr", href: "/restroom-cubicle-in-bulandshahr" },
  { label: "Muzaffarnagar", href: "/restroom-cubicle-in-muzaffarnagar" },
  { label: "Shamli", href: "/restroom-cubicle-in-shamli" },
  { label: "Palwal", href: "/restroom-cubicle-in-palwal" },
  { label: "Jhajjar", href: "/restroom-cubicle-in-jhajjar" },
  { label: "Karnal", href: "/restroom-cubicle-in-karnal" },
  { label: "Hisar", href: "/restroom-cubicle-in-hisar" },
  { label: "Ambala", href: "/restroom-cubicle-in-ambala" },
  { label: "Kurukshetra", href: "/restroom-cubicle-in-kurukshetra" },
  { label: "Yamunanagar", href: "/restroom-cubicle-in-yamunanagar" },
  { label: "Panchkula", href: "/restroom-cubicle-in-panchkula" },
  { label: "Sirsa", href: "/restroom-cubicle-in-sirsa" },
  { label: "Bhiwani", href: "/restroom-cubicle-in-bhiwani" },
  { label: "Jind", href: "/restroom-cubicle-in-jind" },
  { label: "Kaithal", href: "/restroom-cubicle-in-kaithal" },
  { label: "Fatehabad", href: "/restroom-cubicle-in-fatehabad" },
  { label: "Narnaul", href: "/restroom-cubicle-in-narnaul" },
  { label: "Mahendragarh", href: "/restroom-cubicle-in-mahendragarh" },
  { label: "Charkhi Dadri", href: "/restroom-cubicle-in-charkhi-dadri" },
  { label: "Nuh", href: "/restroom-cubicle-in-nuh" },
  { label: "Dharuhera", href: "/restroom-cubicle-in-dharuhera" },
  { label: "Bawal", href: "/restroom-cubicle-in-bawal" },
  { label: "Hansi", href: "/restroom-cubicle-in-hansi" },
  { label: "Tohana", href: "/restroom-cubicle-in-tohana" },
  { label: "Narwana", href: "/restroom-cubicle-in-narwana" },

  { label: "Agra", href: "/restroom-cubicle-in-agra" },
  { label: "Mathura", href: "/restroom-cubicle-in-mathura" },
  { label: "Aligarh", href: "/restroom-cubicle-in-aligarh" },
  { label: "Lucknow", href: "/restroom-cubicle-in-lucknow" },
  { label: "Kanpur", href: "/restroom-cubicle-in-kanpur" },
  { label: "Bareilly", href: "/restroom-cubicle-in-bareilly" },
  { label: "Moradabad", href: "/restroom-cubicle-in-moradabad" },
  { label: "Saharanpur", href: "/restroom-cubicle-in-saharanpur" },
  { label: "Firozabad", href: "/restroom-cubicle-in-firozabad" },
  { label: "Ayodhya", href: "/restroom-cubicle-in-ayodhya" },
  { label: "Prayagraj", href: "/restroom-cubicle-in-prayagraj" },
  { label: "Varanasi", href: "/restroom-cubicle-in-varanasi" },
  { label: "Gorakhpur", href: "/restroom-cubicle-in-gorakhpur" },
  { label: "Jhansi", href: "/restroom-cubicle-in-jhansi" },
  { label: "Rampur", href: "/restroom-cubicle-in-rampur" },
  { label: "Rae Bareli", href: "/restroom-cubicle-in-rae-bareli" },
  { label: "Unnao", href: "/restroom-cubicle-in-unnao" },
  { label: "Etawah", href: "/restroom-cubicle-in-etawah" },
  { label: "Mainpuri", href: "/restroom-cubicle-in-mainpuri" },
  { label: "Shahjahanpur", href: "/restroom-cubicle-in-shahjahanpur" },
  { label: "Bulandshahr", href: "/restroom-cubicle-in-bulandshahr" },
  { label: "Sitapur", href: "/restroom-cubicle-in-sitapur" },
  { label: "Lakhimpur", href: "/restroom-cubicle-in-lakhimpur" },
  { label: "Farrukhabad", href: "/restroom-cubicle-in-farrukhabad" },
  { label: "Sultanpur", href: "/restroom-cubicle-in-sultanpur" },
  { label: "Mirzapur", href: "/restroom-cubicle-in-mirzapur" },
  { label: "Ghazipur", href: "/restroom-cubicle-in-ghazipur" },
  { label: "Jaunpur", href: "/restroom-cubicle-in-jaunpur" },
  { label: "Muzaffarnagar", href: "/restroom-cubicle-in-muzaffarnagar" },
  { label: "Aligarh", href: "/restroom-cubicle-in-aligarh" },

  { label: "Jaipur", href: "/restroom-cubicle-in-jaipur" },
  { label: "Alwar", href: "/restroom-cubicle-in-alwar" },
  { label: "Bhiwadi", href: "/restroom-cubicle-in-bhiwadi" },
  { label: "Bharatpur", href: "/restroom-cubicle-in-bharatpur" },
  { label: "Neemrana", href: "/restroom-cubicle-in-neemrana" },
  { label: "Kota", href: "/restroom-cubicle-in-kota" },
  { label: "Ajmer", href: "/restroom-cubicle-in-ajmer" },
  { label: "Jodhpur", href: "/restroom-cubicle-in-jodhpur" },
  { label: "Udaipur", href: "/restroom-cubicle-in-udaipur" },
  { label: "Bikaner", href: "/restroom-cubicle-in-bikaner" },
  { label: "Sikar", href: "/restroom-cubicle-in-sikar" },
  { label: "Bhilwara", href: "/restroom-cubicle-in-bhilwara" },
  { label: "Sri Ganganagar", href: "/restroom-cubicle-in-sri-ganganagar" },
  { label: "Hanumangarh", href: "/restroom-cubicle-in-hanumangarh" },
  { label: "Chittorgarh", href: "/restroom-cubicle-in-chittorgarh" },

  { label: "Gwalior", href: "/restroom-cubicle-in-gwalior" },
  { label: "Morena", href: "/restroom-cubicle-in-morena" },
  { label: "Shivpuri", href: "/restroom-cubicle-in-shivpuri" },
  { label: "Guna", href: "/restroom-cubicle-in-guna" },
  { label: "Bhopal", href: "/restroom-cubicle-in-bhopal" },
  { label: "Indore", href: "/restroom-cubicle-in-indore" },
  { label: "Ujjain", href: "/restroom-cubicle-in-ujjain" },
  { label: "Jabalpur", href: "/restroom-cubicle-in-jabalpur" },
  { label: "Sagar", href: "/restroom-cubicle-in-sagar" },
  { label: "Ratlam", href: "/restroom-cubicle-in-ratlam" },
  { label: "Dewas", href: "/restroom-cubicle-in-dewas" },
  { label: "Rewa", href: "/restroom-cubicle-in-rewa" },
  { label: "Satna", href: "/restroom-cubicle-in-satna" },
  { label: "Vidisha", href: "/restroom-cubicle-in-vidisha" },
  { label: "Mandsaur", href: "/restroom-cubicle-in-mandsaur" },
];