export const PRODUCTS_CATALOG = [
    {
        slug: 'toilet-cubicle-neo-model',
        name: 'TOILET CUBICLE NEO MODEL',
        category: 'Private Beach Villa',
        location: 'Bali, Indonesia',
        size: '320 m²',
        image: 'https://media.istockphoto.com/id/1206101413/photo/row-of-public-toilet-decorated-with-wooden-partition.jpg?s=612x612&w=0&k=20&c=RPzZ0KfkG6DsxrFjPfYEyWa30BJCkS43ycS-Cfp1LUc=',
        description: 'A tranquil beachfront villa designed to evoke a serene connection between indoor living and organic simplicity.',
        badge: 'Featured Project',
    },
    {
        slug: 'toilet-cubicle-maxi-model',
        name: 'TOILET CUBICLE MAXI MODEL',
        category: 'Restroom Systems',
        location: 'Mumbai, India',
        size: 'Commercial High-Traffic',
        image: 'https://media.istockphoto.com/id/2268278029/photo/modern-public-restroom-interior-with-gray-toilet-stalls-and-wall-mounted-urinals.jpg?s=612x612&w=0&k=20&c=3pNdcCeVknZKzVpUA-z81emj13l4dh-yT4upONjjgQ8=',
        description: '100% moisture-resistant high-pressure laminate partition system with SS 316 anti-vandal hardware.',
        badge: 'Best Seller',
    },
    {
        slug: 'toilet-cubicle-maxi-pro-model',
        name: 'TOILET CUBICLE MAXI PRO MODEL',
        category: 'Luxury Residential',
        location: 'Jakarta, Indonesia',
        size: '240 m²',
        image: 'https://media.istockphoto.com/id/1965427683/photo/public-toilet-in-shopping-mall-city-toilet-separate-cubicles-wooden-door.jpg?s=612x612&w=0&k=20&c=gWC9bc7U4WIErLNWdRPA2QC7Yk6Y83FeRGW4DAwRGxU=',
        description: 'Bespoke marble finishes, warm teakwood textures, and minimalist spatial planning for modern urban living.',
        badge: 'Premium Finish',
    },
    {
        slug: 'toilet-cubicle-duro-model',
        name: 'TOILET CUBICLE DURO MODEL',
        category: 'Corporate Spaces',
        location: 'Singapore',
        size: '500 m²',
        image: 'https://media.istockphoto.com/id/1206101405/photo/row-of-public-toilet-decorated-with-wooden-partition.jpg?s=612x612&w=0&k=20&c=tAVFpifhILw3L0JdNId443byUS-GXp8n-X6IdSpjg1M=',
        description: 'Acoustically insulated modular glass and laminate partitions engineered for high-performance workplaces.',
        badge: 'Acoustic Rated',
    },
    {
        slug: 'toilet-cubicle-duro-pro-model',
        name: 'TOILET CUBICLE DURO PRO MODEL',
        category: 'Boutique Restoration',
        location: 'Medan, Indonesia',
        size: '410 m²',
        image: 'https://media.istockphoto.com/id/1952619672/photo/changing-booth-at-the-swimming-pool.jpg?s=612x612&w=0&k=20&c=F59Dvvlh7mEo4W_nNuKsL03uQnZHgH6cIN3T40DlapI=',
        description: 'Restoring historic architectural grace with modern humidity-resistant stone paneling and custom fittings.',
        badge: 'Architectural Icon',
    },
    {
        slug: 'toilet-cubicle-luron-model',
        name: 'TOILET CUBICLE LURON MODEL',
        category: 'Wellness & Spa',
        location: 'Bangalore, India',
        size: '180 m²',
        image: 'https://media.istockphoto.com/id/1061147274/photo/luxury-brown-public-toilet-with-rows-ceramic-urinal.jpg?s=612x612&w=0&k=20&c=T2DM-xQUBvgOLsxFZQwYVlvG4LnhDTCgcK35aFt0Vn0=',
        description: 'Antibacterial, scratch-resistant wall paneling paired with concealed ceiling-hung cubicle structures.',
        badge: 'Eco Friendly',
    },
];